- params:
    git:
      repoName: frogbotoidc
      branches:
        - main
    scan:
      projects:
        - workingDirs:
          - "Projects/python-fb-example/requirements/"
          pipRequirementsFile: requirements.txt
        
